INSERT INTO departamento VALUES (1, 'Artigas');
INSERT INTO departamento VALUES (2, 'Canelones');
INSERT INTO departamento VALUES (3, 'Cerro Largo');
INSERT INTO departamento VALUES (4, 'Colonia');
INSERT INTO departamento VALUES (5, 'Durazno');
INSERT INTO departamento VALUES (6, 'Flores');
INSERT INTO departamento VALUES (7, 'Florida');
INSERT INTO departamento VALUES (8, 'Lavalleja');
INSERT INTO departamento VALUES (9, 'Maldonado');
INSERT INTO departamento VALUES (10, 'Montevideo');
INSERT INTO departamento VALUES (11, 'Paysandú');
INSERT INTO departamento VALUES (12, 'Río Negro');
INSERT INTO departamento VALUES (13, 'Rivera');
INSERT INTO departamento VALUES (14, 'Rocha');
INSERT INTO departamento VALUES (15, 'Salto');
INSERT INTO departamento VALUES (16, 'San José');
INSERT INTO departamento VALUES (17, 'Soriano');
INSERT INTO departamento VALUES (18, 'Tacuarembó');
INSERT INTO departamento VALUES (19, 'Treinta y Tres');