
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioAgesic", targetNamespace = "http://servicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioAgesic {


    /**
     * 
     * @param arg0
     * @return
     *     returns servicios.DtPersona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPersona", targetNamespace = "http://servicios/", className = "servicios.ObtenerPersona")
    @ResponseWrapper(localName = "obtenerPersonaResponse", targetNamespace = "http://servicios/", className = "servicios.ObtenerPersonaResponse")
    public DtPersona obtenerPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
