
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioAgesicService", targetNamespace = "http://servicios/", wsdlLocation = "https://agesic-nodo.herokuapp.com/agesic-nodo/ServicioAgesic?wsdl")
public class ServicioAgesicService
    extends Service
{

    private final static URL SERVICIOAGESICSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOAGESICSERVICE_EXCEPTION;
    private final static QName SERVICIOAGESICSERVICE_QNAME = new QName("http://servicios/", "ServicioAgesicService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://agesic-nodo.herokuapp.com/agesic-nodo/ServicioAgesic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOAGESICSERVICE_WSDL_LOCATION = url;
        SERVICIOAGESICSERVICE_EXCEPTION = e;
    }

    public ServicioAgesicService() {
        super(__getWsdlLocation(), SERVICIOAGESICSERVICE_QNAME);
    }

    public ServicioAgesicService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOAGESICSERVICE_QNAME, features);
    }

    public ServicioAgesicService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOAGESICSERVICE_QNAME);
    }

    public ServicioAgesicService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOAGESICSERVICE_QNAME, features);
    }

    public ServicioAgesicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioAgesicService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioAgesic
     */
    @WebEndpoint(name = "ServicioAgesicPort")
    public ServicioAgesic getServicioAgesicPort() {
        return super.getPort(new QName("http://servicios/", "ServicioAgesicPort"), ServicioAgesic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioAgesic
     */
    @WebEndpoint(name = "ServicioAgesicPort")
    public ServicioAgesic getServicioAgesicPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "ServicioAgesicPort"), ServicioAgesic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOAGESICSERVICE_EXCEPTION!= null) {
            throw SERVICIOAGESICSERVICE_EXCEPTION;
        }
        return SERVICIOAGESICSERVICE_WSDL_LOCATION;
    }

}
