
package webservicesoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VacunatorioServicioService", targetNamespace = "http://webServiceSoap/", wsdlLocation = "http://localhost:8080/comp-cent-web/heroku-wsdl/HerokuVacunatorio.wsdl")
public class VacunatorioServicioService
    extends Service
{

    private final static URL VACUNATORIOSERVICIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException VACUNATORIOSERVICIOSERVICE_EXCEPTION;
    private final static QName VACUNATORIOSERVICIOSERVICE_QNAME = new QName("http://webServiceSoap/", "VacunatorioServicioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/comp-cent-web/heroku-wsdl/HerokuVacunatorio.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VACUNATORIOSERVICIOSERVICE_WSDL_LOCATION = url;
        VACUNATORIOSERVICIOSERVICE_EXCEPTION = e;
    }

    public VacunatorioServicioService() {
        super(__getWsdlLocation(), VACUNATORIOSERVICIOSERVICE_QNAME);
    }

    public VacunatorioServicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VACUNATORIOSERVICIOSERVICE_QNAME, features);
    }

    public VacunatorioServicioService(URL wsdlLocation) {
        super(wsdlLocation, VACUNATORIOSERVICIOSERVICE_QNAME);
    }

    public VacunatorioServicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VACUNATORIOSERVICIOSERVICE_QNAME, features);
    }

    public VacunatorioServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VacunatorioServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VacunatorioServicio
     */
    @WebEndpoint(name = "VacunatorioServicioPort")
    public VacunatorioServicio getVacunatorioServicioPort() {
        return super.getPort(new QName("http://webServiceSoap/", "VacunatorioServicioPort"), VacunatorioServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VacunatorioServicio
     */
    @WebEndpoint(name = "VacunatorioServicioPort")
    public VacunatorioServicio getVacunatorioServicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServiceSoap/", "VacunatorioServicioPort"), VacunatorioServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VACUNATORIOSERVICIOSERVICE_EXCEPTION!= null) {
            throw VACUNATORIOSERVICIOSERVICE_EXCEPTION;
        }
        return VACUNATORIOSERVICIOSERVICE_WSDL_LOCATION;
    }

}
