
package webservicesoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VacunatorioServicio", targetNamespace = "http://webServiceSoap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VacunatorioServicio {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarVacunatorios", targetNamespace = "http://webServiceSoap/", className = "webservicesoap.ListarVacunatorios")
    @ResponseWrapper(localName = "listarVacunatoriosResponse", targetNamespace = "http://webServiceSoap/", className = "webservicesoap.ListarVacunatoriosResponse")
    public List<Integer> listarVacunatorios();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns webservicesoap.DtMsjVacunatorio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarVacunadores", targetNamespace = "http://webServiceSoap/", className = "webservicesoap.AsignarVacunadores")
    @ResponseWrapper(localName = "asignarVacunadoresResponse", targetNamespace = "http://webServiceSoap/", className = "webservicesoap.AsignarVacunadoresResponse")
    public DtMsjVacunatorio asignarVacunadores(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Integer> arg2);

}
